---
name: rtlamr2mqtt
version: 2025.6.3
slug: rtlamr2mqtt
panel_icon: mdi:gauge
description: RTLAMR to MQTT Bridge
startup: application
boot: auto
map:
  - config:rw
url: https://github.com/allangood/rtlamr2mqtt
uart: true
udev: true
usb: true
host_network: false
hassio_api: true
arch:
  - amd64
  - aarch64
services:
  - mqtt:need
options:
  general:
    sleep_for: 60
    verbosity: info
  custom_parameters: {}
  mqtt:
    ha_autodiscovery_topic: homeassistant
    ha_status_topic: homeassistant/status
    base_topic: "rtlamr"
  meters:
    - id: 22222222
      protocol: r900
      name: my_energy_meter
      format: "######.###"
      # device_class on HA
      device_class: energy

schema:
  general:
    sleep_for: "int?"
    verbosity: "list(debug|info|warning|critical|none)?"
    device_id: "match((^0|^(0[xX])?[A-Fa-f0-9]+:(0[xX])?[A-Fa-f0-9]+$))?"
    rtltcp_host: match(([\w\d\.]+):(\d+))?
  mqtt:
    host: "str?"
    port: "int?"
    user: "str?"
    password: str?
    tls_enabled: "bool?"
    tls_insecure: "bool?"
    tls_ca: "str?"
    tls_cert: "str?"
    tls_keyfile: "str?"
    ha_autodiscovery_topic: "str?"
    ha_status_topic: "str?"
    base_topic: "str?"
  custom_parameters:
    rtltcp: "str?"
    rtlamr: "str?"
  meters:
    - id: int
      protocol: list(idm|netidm|r900|r900bcd|scm|scm+)
      name: "str"
      format: "str?"
      unit_of_measurement: "str?"
      icon: "str?"
      device_class: list(none|current|energy|gas|power|water)
      state_class: list(measurement|total|total_increasing)?
      expire_after: int?
      force_update: bool?
