name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["allangood/rtlmr2mqtt"]
assignees:
  - allangood
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Try to be more descriptive than 'it doesn't work' or 'it is broken'."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version used
      description: What is the version of rtlmr2mqtt you are using?
      placeholder: 2025.6.1
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: How are you using rtlmr2mqtt?
      multiple: false
      options:
        - Home Assitant Add-on
        - Stand alone Docker
  - type: textarea
    id: config
    attributes:
      label: Configuration file
      description: Please copy and paste your configuration file here. Remove any sensitive data from it.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell